plugins: rubocop-rake
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "test/_plugins/jekyll_sqlite_generator.rb"
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 15